name: portfolio
description: "Personal Portfolio Website"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_riverpod: ^3.0.3
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.3.2
  http: ^1.6.0
  intl: ^0.20.2
  meta_seo: ^3.0.9
  share_plus: ^10.1.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/data/
  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf
